### ISSUE TITLE
Error while starting the queue: TypeError: Missing 'sharedAccessKeyName' in configuration

### ISSUE THREAD

**Issue by gh0st** [docusign/connect-node-worker-azure#1]
```
$ npm start

> connect_node_worker_azure@1.0.0 start C:\Users\user\source\Workspaces\connect-node-worker-azure
> node --require dotenv/config index.js

checkToken: Starting up--need an accessToken
Obtained an access token. Continuing...
Thu, 26 Mar 2020 03:58:13 GMT Starting queue worker

Thu, 26 Mar 2020 03:58:13 GMT Error while starting the queue:
TypeError: Missing 'sharedAccessKeyName' in configuration
    at Object.validate (C:\Users\user\source\Workspaces\connect-node-worker-azure\node_modules\@azure\amqp-common\dist\index.js:1596:19)
    at Function.createFromConnectionString (C:\Users\user\source\Workspaces\connect-node-worker-azure\node_modules\@azure\service-bus\dist\index.js:6038:37)
    at startQueue (C:\Users\user\source\Workspaces\connect-node-worker-azure\index.js:59:29)
    at listenForever (C:\Users\user\source\Workspaces\connect-node-worker-azure\index.js:80:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
I get this error when trying to `npm start` my worker. I've set the rest of the `ds_configuration.js` appropriately I believe.

**Comment by LarryKlugerDS** [comment]
I apologize for the slow response. Have you solved this problem? 
If not, I will look into it.
Thank you,
Larry

**Comment by gh0st** [comment]
> I apologize for the slow response. Have you solved this problem?
> If not, I will look into it.
> Thank you,
> Larry

Yep, all taken care of, thank you! I just don't think I was referencing my config correctly.
